(()=>{const header=document.querySelector('.header');const links=[...document.querySelectorAll('a[href^="#"]')];links.forEach(a=>a.addEventListener('click',e=>{const el=document.querySelector(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth',block:'start'})}}));const reveal=[...document.querySelectorAll('section,.service-list a,.work-grid article,.steps div,.proof div')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});reveal.forEach(e=>{e.classList.add('reveal');io.observe(e)});window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20),{passive:true});const h=document.querySelector('.hamb');h?.addEventListener('click',()=>{document.body.classList.toggle('menu-open');h.textContent=document.body.classList.contains('menu-open')?'×':'☰'});
const style=document.createElement('style');style.textContent=`.nr-insights .nr-blog-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:55px}.nr-insights .nr-blog-img{height:300px;border-radius:15px;position:relative;overflow:hidden;margin-bottom:22px;background-size:cover;background-position:center}.nr-insights .b1{background-image:linear-gradient(180deg,transparent 35%,rgba(8,12,15,.78)),url('/visuals/strategy.svg')!important}.nr-insights .b2{background-image:linear-gradient(180deg,transparent 35%,rgba(8,12,15,.78)),url('/visuals/performance.svg')!important}.nr-insights .b3{background-image:linear-gradient(180deg,transparent 35%,rgba(8,12,15,.78)),url('/visuals/social.svg')!important}.nr-insights .nr-blog-img:after{display:none!important}.nr-insights .nr-blog-grid article{overflow:hidden}.nr-insights .nr-blog-img{transition:transform .7s ease}.nr-insights .nr-blog-grid article:hover .nr-blog-img{transform:scale(1.035)}@media(max-width:800px){.nr-insights .nr-blog-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.nr-insights .nr-blog-grid{grid-template-columns:1fr}.nr-insights .nr-blog-img{height:250px}}`;document.head.appendChild(style);
const seo={
'/':{title:'Next Resource | Digital Marketing Agency in Ranchi',description:'Next Resource is a digital marketing agency in Ranchi, Jharkhand helping businesses grow through social media, performance ads, branding, web development, SEO and customer outreach.'},
'/services.html':{title:'Digital Marketing Services in Ranchi | Next Resource',description:'Explore digital marketing services from Next Resource in Ranchi: social media, performance marketing, branding, web and app development, SEO, WhatsApp, SMS and calling.'},
'/work.html':{title:'Digital Marketing Work & Case Studies | Next Resource',description:'See selected branding, performance marketing, media, hospitality, SEO and digital growth work from Next Resource, a Ranchi-based digital marketing agency.'},
'/blog.html':{title:'Digital Marketing Blog & SEO Insights | Next Resource',description:'Practical digital marketing, SEO, social media, branding, advertising and website growth insights for Indian businesses from Next Resource in Ranchi.'},
'/post.html':{title:'How Local SEO Helps Ranchi Businesses Get Found | Next Resource',description:'A practical local SEO guide for Ranchi businesses covering Google Business Profile, website relevance, local intent, content and conversion actions.'},
'/gallery.html':{title:'Branding, Campaign & Digital Work Gallery | Next Resource',description:'Explore selected visual work across branding, campaigns, hospitality, digital marketing and content from Next Resource.'},
'/about.html':{title:'About Next Resource | Digital Marketing Agency in Ranchi',description:'Learn about Next Resource, a Ranchi, Jharkhand digital marketing agency built to give lean Indian businesses strategy, creative, media, technology and SEO support.'},
'/contact.html':{title:'Get a Digital Marketing Quote in Ranchi | Next Resource',description:'Contact Next Resource in Ranchi, Jharkhand for digital marketing, SEO, social media, performance ads, branding, web development and customer outreach.'},
'/case-study.html':{title:'Case Study | Next Resource',description:'Next Resource case study template.',noindex:true}
};
const path=location.pathname.replace(/\/+$/,'')||'/';const cfg=seo[path]||seo['/'];const up=(name,content,attr='name')=>{let el=document.head.querySelector(`meta[${attr}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,name);document.head.appendChild(el)}el.setAttribute('content',content)};
document.title=cfg.title;up('description',cfg.description);up('robots',cfg.noindex?'noindex,follow':'index,follow');up('og:type',path==='/post.html'?'article':'website','property');up('og:title',cfg.title,'property');up('og:description',cfg.description,'property');up('og:url',location.origin+(path==='/'?'':path),'property');up('og:site_name','Next Resource','property');up('twitter:card','summary');up('twitter:title',cfg.title);up('twitter:description',cfg.description);
let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=location.origin+(path==='/'?'':path);
if(cfg.noindex)return;
const business={"@type":"LocalBusiness","@id":"https://nextresource.in/#business","name":"Next Resource","url":"https://nextresource.in/","telephone":"+919770996996","email":"nextresourceindia@gmail.com","address":{"@type":"PostalAddress","addressLocality":"Ranchi","addressRegion":"Jharkhand","postalCode":"834001","addressCountry":"IN"},"areaServed":[{"@type":"City","name":"Ranchi"},{"@type":"State","name":"Jharkhand"},{"@type":"Country","name":"India"}],"knowsAbout":["Digital Marketing","SEO","Social Media Marketing","Performance Marketing","Branding","Web Development","WhatsApp Marketing"]};
const schemas=[];if(path==='/'){schemas.push({"@context":"https://schema.org","@type":"WebSite","name":"Next Resource","url":"https://nextresource.in/","description":cfg.description},business);}else{schemas.push({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://nextresource.in/"},{"@type":"ListItem","position":2,"name":document.title.split('|')[0].trim(),"item":canonical.href}]});}
if(path==='/services.html')schemas.push({"@context":"https://schema.org","@type":"ItemList","name":"Digital Marketing Services","itemListElement":["Social & Content","Performance Ads","Branding & Design","Web & App Development","SEO","Bulk WhatsApp, SMS & Calling"].map((name,i)=>({"@type":"ListItem","position":i+1,"name":name}))});
if(path==='/post.html')schemas.push({"@context":"https://schema.org","@type":"Article","headline":cfg.title.replace(' | Next Resource',''),"description":cfg.description,"author":{"@type":"Organization","name":"Next Resource","url":"https://nextresource.in/"},"publisher":{"@type":"Organization","name":"Next Resource","url":"https://nextresource.in/"},"mainEntityOfPage":canonical.href});
schemas.forEach(data=>{const s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify(data);document.head.appendChild(s)});
})();