const http=require('http'),fs=require('fs'),path=require('path'),cms=require('./cms-backend');
const pages=require('./blog-pages').make(cms.read);
const port=process.env.PORT||3000,root=__dirname;
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};
const server=http.createServer(async(req,res)=>{const p=(req.url||'/').split('?')[0];try{if(await cms.route(req,res,p))return}catch(e){console.error(e);res.writeHead(500);return res.end('Server error')}
if(p==='/blog'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(pages.index())}
if(p.startsWith('/blog/')){const x=pages.posts().find(v=>v.slug===decodeURIComponent(p.slice(6)));if(!x){res.writeHead(404);return res.end('Article not found')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(pages.post(x))}
if(p==='/sitemap.xml'){const base='https://next-resource-live.onrender.com',ps=pages.posts();res.writeHead(200,{'Content-Type':'application/xml'});return res.end(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url><url><loc>${base}/blog</loc></url>${ps.map(x=>`<url><loc>${base}/blog/${encodeURIComponent(x.slug)}</loc><lastmod>${x.updatedAt.slice(0,10)}</lastmod></url>`).join('')}</urlset>`)}
if(p==='/robots.txt'){res.writeHead(200,{'Content-Type':'text/plain'});return res.end('User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /api/\nSitemap: https://next-resource-live.onrender.com/sitemap.xml\n')}
let file=p==='/'?'/index.html':p;if(file==='/admin'||file==='/admin/')file='/admin.html';const full=path.join(root,file);if(!full.startsWith(root)||!fs.existsSync(full)){res.writeHead(404);return res.end('Not found')};if(file==='/index.html'){let html=fs.readFileSync(full,'utf8');let site={heroImage:'/visuals/hero-clean.svg',sections:{}};try{site=cms.readSite()}catch{}html=html.replace('</head>',`<script>window.NR_SITE_CONFIG=${JSON.stringify(site).replace(/</g,'\\u003c')};</script></head>`);html=html.replace('</body>','<script src="/brand-content.js?v=20260911" defer></script><script src="/blog-link.js" defer></script><script src="/site-runtime.js?v=20260911" defer></script></body>');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return res.end(html)}if(file==='/admin.html'){let html=fs.readFileSync(full,'utf8');html=html.replace('</body>','<script src="/site-builder.js?v=20260911"></script></body>');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return res.end(html)}res.writeHead(200,{'Content-Type':types[path.extname(full).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(full).pipe(res)});
server.listen(port,'0.0.0.0',()=>console.log('Next Resource CMS server listening on '+port));
